name: payoneclick
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"


dependencies:
  flutter:
    sdk: flutter


  json_annotation: ^4.8.1
  cupertino_icons: ^1.0.6
  curved_labeled_navigation_bar: ^2.0.2
  http: ^0.13.4
  dio: ^4.0.4
  cached_network_image: ^3.2.0
  table_calendar: ^3.0.8
  html: ^0.15.0
  intl: ^0.17.0
  share: ^2.0.4
  screenshot: ^2.5.0
  path_provider: ^2.0.11
  url_launcher: ^6.1.11
  flutter_phone_direct_caller: ^2.1.0


dev_dependencies:
  #this below is testing
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  #this above is testing
  flutter_test:
    sdk: flutter


  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  # To add assets to your application, add an assets section, like this:
  assets:
    - image/icon1.png
    - image/pagedesign.png
    - image/Ellipse.png
    - image/Sort.png
    - image/Ellipse2.png
    - image/payment.png
    - image/Maskgroup.png
    - image/Group8688.png
    - image/Group8689.png
    - image/Group8690.png
    - image/Group8693.png
    - image/Group8695.png
    - image/Group8706.png
    - image/Group8703.png
    - image/Group8699.png
    - image/Group8705.png
    - image/Group8704.png
    - image/Maskgroup2.png
    - image/PNG3.png
    - image/


  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
